sudo: required
language: python
python:
  - "2.7"
install:
  - pip install --user awscli chalice
  - pip install -r requirements.txt
# safelist
branches:
  only:
  - staging

script:
  - mkdir ~/.aws/
  - touch ~/.aws/credentials
  - echo "[default]" >> ~/.aws/credentials
  - echo "aws_access_key_id = $AWS_ID" >> ~/.aws/credentials
  - echo "aws_secret_access_key = $AWS_SECRET" >> ~/.aws/credentials
  - touch ~/.aws/config
  - echo "[default]" >> ~/.aws/config
  - echo "output = json" >> ~/.aws/config
  - echo "region = ap-southeast-2" >> ~/.aws/config
  - sudo chalice deploy
